eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lin-jim/spring-cloud
          searchPaths: helloworld.config
          username: lin-jim
          password: Ljm040...
  application:
    name: config-server
    